import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./context/AuthContext";
import { ModalProvider } from "./context/ModalContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <ModalProvider>
      <html>
        <body className="bg-gray-100 dark:bg-gray-900 relative">
        <Navbar />
        <main>
          {children}
        </main>
        </body>
      </html>
      </ModalProvider>
    </AuthProvider>
  );
}
